FROM node:22-bookworm-slim AS base
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG CRON_SECRET
ARG LINE_CHANNEL_ID
ARG LINE_CHANNEL_SECRET
ARG LINE_LOGIN_CHANNEL_ID
ARG LINE_LOGIN_CHANNEL_SECRET
ARG LINE_LOGIN_REDIRECT_URI
ARG LINE_NOTIFICATION_TOKEN
ARG VAPID_PUBLIC_KEY
ARG VAPID_PRIVATE_KEY
ARG SUPABASE_TASK_PHOTO_BUCKET

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV CRON_SECRET=$CRON_SECRET
ENV LINE_CHANNEL_ID=$LINE_CHANNEL_ID
ENV LINE_CHANNEL_SECRET=$LINE_CHANNEL_SECRET
ENV LINE_LOGIN_CHANNEL_ID=$LINE_LOGIN_CHANNEL_ID
ENV LINE_LOGIN_CHANNEL_SECRET=$LINE_LOGIN_CHANNEL_SECRET
ENV LINE_LOGIN_REDIRECT_URI=$LINE_LOGIN_REDIRECT_URI
ENV LINE_NOTIFICATION_TOKEN=$LINE_NOTIFICATION_TOKEN
ENV VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
ENV VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
ENV SUPABASE_TASK_PHOTO_BUCKET=$SUPABASE_TASK_PHOTO_BUCKET
RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV APP_BASE_URL=https://teamtask.do-nexus.co.jp
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
